= *eXo data-injectors*

A *data injectors* for eXo that allows administrators to inject content types
 such as: social (users, connections, spaces, membership),forum (post, topic), wiki (wiki page), ecms (pdf, doc, xls,... document), FAQ(category,questions,answers..)

== Installation
 * Start by downloading eXo Platform 4.4 and install the add-on :

 cd <PLF_ROOT_DIR>
 ./addon install exo-data-injectors

== How to inject

All the injection commands were designed to be invoked via rest service.
The service is named "org.exoplatform.services.bench.DataInjectorService"
and registered normally to portal container as general component.

The format of request link is:

 http://{domain}/{rest}/private/bench/{inject\|reject}/{type}?\[params\]

So, simply:

1: login to the PLF first

2: call rest services

=== SOCIAL Inject
We will describe how to use data injectors in eXo Social

*inject identity*

|===
|Parameter | Type | Description | Default value

|number
|mandatory
|The amount of injected users
|


|prefix
|optional
|Define the user prefix
| "bench.user"

|pattern
|optional
|Define the user suffix
| 0000

|===


 http://localhost:8080/rest/private/bench/inject/identity?pattern=0000&number=100&prefix=abc

 --> identity injected successfully!!!

* This call will generate 100 users with prefix=abc

-------
The new version will not use a prefix and a counter for users. the request
http://localhost:8080/rest/private/bench/inject/identity?number=100
will create 100 users with a random firstname and lastname. The user name is first letter of firstname + lastname
Each time we call this request, 100 new users are created.

Then, to the user list, we add a this web service
http://localhost:8080/rest/datalisting/identities
The result is

    acharles,exo
    adunn,exo
    ahiggins,exo
    amalone,exo
    amay,exo

and can be copy/paste in a CSV file for bench purpose.

To list searchTerms for independent :
http://localhost:8080/rest/datalisting/searchTerms
The result is

    Root
    Lindsey
    Craft
    Lenox
    Motors
    Wayne
    Guerrero
    Joyce

It take all distinct firstname, lastname, and unique word for all company names.
-------

*Inject Social Profile (custom)*
|===
|Parameter | Type | Description | Default value

|fromUser
|optional
|The index of the first user to populate
| 0


|toUser
|optional
|The index of the last user to populate
| last user index
|===

 http://localhost:8080/rest/private/bench/inject/profile?fromUser=0&toUser=100


*inject space*

|===
|Parameter |Type |Description |Default value

|fromUser
|optional
|The begin of the range
|

|toUser
|optional
|The end of the range
|

|number
|mandatory
|The amount of injected spaces for each user or space
|

|userPrefix
|optional
|Define the user prefix
|"bench.user"


|spacePrefix
|optional
|Define the space prefix
|"bench.space"

|===

  http://localhost:8080/rest/private/bench/inject/space?number=10&fromUser=1000&toUser=1009

 --> space injected successfully!!!

* This call will generate for each user in the range [1000 - 1009] 10 spaces.. So 100 spaces will be created

Each user in the range will be the owner (manager) of the space.

*inject membership*

|===
|Parameter |Type |Description |Default value

|type
|mandatory
|must be set as 'member' or 'manager'
|

|fromUser
|mandatory
|The begin of the range
|

|toUser
|mandatory
|The end of the range
|


|userPrefix
|optional
|Define the user prefix
|"bench.user"

|fromSpace
|mandatory
|The begin of the range
|

|toSpace
|mandatory
|The end of the range
|

|spacePrefix
|optional
|Define the space prefix
|"bench.space"

|===

 http://localhost:8080/rest/private/bench/inject/membership?type=member&fromUser=100&toUser=120&userPrefix=bench.user&fromSpace=10&toSpace=20&spacePrefix=bench.space

 --> membership injected successfully!!!

* This call will add each user in the range [100 - 120] to be member for each space in range [10 - 20] with prefix is bench.space


*inject activity*

|===
|Parameter |Type |Description |Default value

|fromUser
|mandatory
|The begin of the range
|

|toUser
|mandatory
|The end of the range
|

|number
|mandatory
|The amount of injected activities for each user
|

|type
|mandatory
|must be set as 'user' or 'space'
|

|userPrefix
|optional
|Define the user prefix
|"bench.user"

|spacePrefix
|optional
|Define the space prefix
|"bench.space"

|===


** for user

 http://localhost:8080/rest/private/bench/inject/activity?number=2&fromUser=0000&toUser=0019&type=user&userPrefix=abc

 --> activity injected successfully!!!

 * This call will generate for each user in the range [0000 - 0019] 2 activities..So 40 activities will be created

** for space

  http://localhost:8080/rest/private/bench/inject/activity?number=5&fromUser=0010&toUser=0049&type=space&userPrefix=abc&spacePrefix=space

 --> activity injected successfully!!!

 * This call will generate for each space in the range [0010 - 0049] 5 activities..So 200 activities will be created


*inject activity mention*


|===
|Parameter  |Type |Description |Default value

|fromUser
|mandatory
|The begin of the range
|

|toUser
|mandatory
|The end of the range
|

|number
|mandatory
|The amount of injected activities for each user
|

|mentioner
|mandatory
|must be set as remoteId who has been mentioned
|

|userPrefix
|optional
|Define the user prefix
|"bench.user"

|===

   http://localhost:8080/rest/private/bench/inject/mentioner?number=2&fromUser=0020&toUser=0030&mentioner=abc0050&userPrefix=abc

 --> mentioner injected successfully!!!


*inject relationship*


|===
|Parameter |Type |Description |Default value

|fromUser
|mandatory
|The begin of the range
|

|toUser
|mandatory
|The end of the range
|

|number
|mandatory
|The amount of injected relationships for each user
|

|prefix
|optional
|Define the user prefix
|"bench.user"

|===
  http://localhost:8080/rest/private/bench/inject/relationship?number=19&fromUser=5100&toUser=5119&type=user

 * This call will generate for each user in the range [5100 - 5119] 19 relations


=== FORUM Inject

We will describe how to use data injectors in eXo Forum

*inject profile*

|===
|Parameter |Type |Description |Default value

|number
|mandatory
|The amount of injected users
|

|prefix
|optional
|Define the user prefix
|"bench.user"
|===

 http://localhost:8080/rest/private/bench/inject/forumProfile?number=100&prefix=abc.user

 --> forumProfile injected successfully!!!

* This call will generate 100 users

*inject category*

|===
|Parameter |Type |Description |Default value

|number
|mandatory
|The amount of injected categories for each user
|

|fromUser
|mandatory
|The begin of the range
|

|toUser
|mandatory
|The end of the range
|

|userPrefix
|optional
|Define the user prefix
| "bench.user"

|catPrefix
|optional
|Define the category prefix
|"bench.cat"

|===

 http://localhost:8080/rest/private/bench/inject/forumCategory?number=10&fromUser=1000&toUser=1009

 --> forumCategory injected successfully!!!

* This call will generate for each user in the range [1000 - 1009] 10 categories..So 100 categories will be created

*inject forum*

|===
|Parameter |Type |Description |Default value

|number
|mandatory
|The amount of injected forum for each category
|

|forumPrefix
|optional
|Define the forum prefix
|"bench.forum"

|toCat
|mandatory
|Injected forum to category
|

|catPrefix
|optional
|Define the category prefix
|"bench.category"

|===

 http://localhost:8080/rest/private/bench/inject/forumForum?number=4&toCat=15&catPrefix=abc.cat&forumPrefix=abc.forum

 --> forumForum injected successfully!!!

* This call will generate 4 forums for category at 15 position


*inject topic*

|===
|Parameter |Type |Description |Default value

|number
|mandatory
|The amount of injected topic own by each user in range into each forum in range
|

|topicPrefix
|optional
|Define the topic prefix
|"bench.topic"

|fromUser
|mandatory
|The begin of the range
|

|toUser
|mandatory
|The end of the range
|

|userPrefix
|optional
|Define the user prefix
| "bench.user"

|toForum
|mandatory
|Injected topic to forum
|

|forumPrefix
|optional
|Define the forum prefix
|"bench.forum"
|===

 http://localhost:8080/rest/private/bench/inject/forumTopic?number=10&topicPrefix=abc.topic&fromUser=1000&toUser=1009&userPrefix=abc.user&toForum=19&forumPrefix=abc.forum


 --> forumTopic injected successfully!!!

* This call will generate for each user in the range [1000 - 1009] 10 topics into to forum at 19 position ..So 100 topics will be created

*inject post*

|===
|Parameter |Type |Description |Default value

|number
|mandatory
|The amount of injected post for each users in range into each topics
|

|postPrefix
|optional
|Define the post prefix
|"bench.post"

|fromUser
|mandatory
|The begin of the range
|

|toUser
|mandatory
|The end of the range
|

|userPrefix
|optional
|Define the user prefix
|"bench.user"

|toTopic
|mandatory
|Injected post to topic
|

|topicPrefix
|optional
|Define the topic prefix
|"bench.topic"
|===


 http://localhost:8080/rest/private/bench/inject/forumPost?number=10&postPrefix=abc.post&fromUser=1000&toUser=1009&userPrefix=abc.user&toTopic=19&topicPrefix=abc.topic

 --> forumPost injected successfully!!!

* This call will generate for each user in the range [1000 - 1009] 10 posts into for each topic at 19 position..So 100 posts will be created


*inject membership*

|===
|Parameter |Type |Description |Default value

|type
|mandatory
|must be set as 'category', 'forum', or 'topic'
|

|toType
|mandatory
|Determines index of type for injection. ex: '5'
|

|typePrefix
|mandatory
|Define type of type prefix. ex: 'cat.forum' => for type is 'category'
|

|fromUser
|mandatory
|The begin of the range
|

|toUser
|mandatory
|The end of the range
|

|userPrefix
|optional
|Define the user prefix
|"bench.user"

|===

 http://localhost:8080/rest/private/bench/inject/forumMembership?type=category&toType=5&typePrefix=abc.cat&fromUser=1000&toUser=1009&userPrefix=abc.user

 --> forumMembership injected successfully!!!

* This call will generate 10 memberships to category type with name is 'abc.cat5'.

*inject attachment*

|===
|Parameter |Type |Description  |Default value

|number
|mandatory
|The amount of injected attachment for each posts in range
|

|postPrefix
|optional
|Define the post prefix
|"bench.post"

|fromPost
|mandatory
|The begin of the range
|

|toPost
|mandatory
|The end of the range
|

|byteSize
|optional
|Define the size of attachment
| 100 bytes

|===


 http://localhost:8080/rest/private/bench/inject/forumAttachment?number=10&postPrefix=abc.post&fromPost=1000&toPost=1019&byteSize=50

 --> forumAttachment injected successfully!!!

* This call will generate for each post in the range [1000 - 1019] 10 attachments..So 200 attachments will be created  with total size = 10000 bytes


=== TASK Inject


We will describe how to use data injectors in eXo TASK


==== Parameters


|===
|Parameter |Type |Description |Default value

|nbProject
|optional
|Number of project per user/space
|15

|nbTaskPerProject
|optional
|Number of tasks in a project
|42

|nbIncomingTask
|optional
|Number of tasks without project per user
|10

|nbTagPerTask
|optional
|Number of tags per task
|2

|nbComPerTask
|optional
|Number of comments per task
|2

|perCompleted
|optional
|Percentage of tasks completed
|70

|type
|optional
|Type of injecting: "user" or "space"
|"user"

|from
|optional
|The begin of the range
|0

|to
|optional
|The end of the range
|10

|prefix
|optional
|Define the user prefix
|"bench.space" if type = "space", "bench.user" otherwise

|suffix
|optional
|Define the user suffix (How many digit after prefix)
|4
|===


*Default for user tasks*

* Generate for 10 users (from bench.user0000 to bench.user0009) 15 projects with 42 tasks in + 10 incoming tasks (tasks without project).
 Each tasks have 2 tags and 2 comments.
 70% of tasks are completed

 http://localhost:8080/rest/private/bench/inject/PersonnalTaskInjector

 --> PersonnalTaskInjector injected successfully!!!


*Specific for user tasks*

 * Generate for 10 users (from abcuser000010 to abcuser000019) **15 projects** with **42 tasks** in + 10 incoming tasks (tasks without project).
   Each tasks have 2 tags and 2 comments.
   70% of tasks are completed.

  http://localhost:8080/rest/private/bench/inject/PersonnalTaskInjector?prefix=abcuser&suffix=6&from=10&to=20

  --> PersonnalTaskInjector injected successfully!!!


 * Generate for 10 users (from bench.user0000 to bench.user0009) **30 projects** with **10 tasks** in + 5 incoming tasks (tasks without project).
   Each tasks have 3 tags and 15 comments.
    70% of tasks are completed.

  http://localhost:8080/rest/private/bench/inject/PersonnalTaskInjector?nbProject=30&nbTaskPerProject=10&nbIncomingTask=5&nbTagPerTask=3&nbComPerTask=15

  --> PersonnalTaskInjector injected successfully!!!


 * Generate for 10 users (from bench.user0000 to bench.user0009) **15 projects** with **42 tasks** in + 10 incoming tasks (tasks without project).
   Each tasks have 2 tags and 2 comments.
   0% of tasks are completed

 http://localhost:8080/rest/private/bench/inject/PersonnalTaskInjector?perCompleted=0

 --> PersonnalTaskInjector injected successfully!!!

*Default for space tasks*

 * Generate for 10 space (from benchspace0000 to benchspace0009) **15 projects** with **42 tasks** in.
   Each tasks have 2 tags and 2 comments.
   70% of tasks are completed.

 http://localhost:8080/rest/private/bench/inject/PersonnalTaskInjector?type=space

 --> PersonnalTaskInjector injected successfully!!!



=== FAQ Inject

We will describe how to use data injectors in eXo FAQ

*inject profile*

|===
|Parameter |Type |Description |Default value

|number
|mandatory
|The amount of injected users
|

|userPrefix
|optional
|Define the user prefix
|"bench.user"

|===

 http://localhost:8080/rest/private/bench/inject/faqProfile?number=10&userPrefix=abc.user

  --> faqProfile injected successfully!!!

 * This call will generate 10 users which user prefix is "abc.user"

*inject category*

|===
|Parameter |Type |Description |Default value

|number
|mandatory
|The amount of injected categories
|

|catPrefix
|optional
|Define the category prefix
|"bench.cat"
|===


   http://localhost:8080/rest/private/bench/inject/faqCategory?number=10&catPrefix=abc.cat

  --> faqCategory injected successfully!!!

 * This call will generate 10 categories which category prefix is "abc.cat".


*inject question*

|===
|Parameter |Type |Description |Default value

|number
|mandatory
|The amount of injected questions for each category
|

|catPrefix
|optional
|Define the category prefix
|"bench.cat"

|toCat
|mandatory
|The category which will be used to inject questions
|

|userPrefix
|optional
|Define the user prefix
| "bench.user"

|toUser
|mandatory
|The user who owns the injected question
|

|quesPrefix
|optional
|Define the question prefix
| "bench.ques"

|===


   http://localhost:8080/rest/private/bench/inject/faqQuestion?number=10&catPrefix=abc.cat&toCat=0&userPrefix=abc.user&toUser=1&quesPrefix=abc.ques

   --> faqQuestion injected successfully!!!

 * This call will generate 10 questions which question prefix is "abc.ques" to category "abc.cat0" which owns by user "abc.user1".


*inject answer*

|===
|Parameter |Type |Description |Default value

|number
|mandatory
|The amount of injected answers
|

|fromQues
|mandatory
|The begin of the question range which injected answers are added to
|

|toQues
|mandatory
|The end of the question range which injected answers are added to
|

|quesPrefix
|optional
| Define the question prefix
|"bench.ques"

|answerPrefix
|optional
 |Define the answer prefix
 |"bench.answer"
|===


   http://localhost:8080/rest/private/bench/inject/faqAnswer?number=10&fromQues=0&toQues=2&quesPrefix=abc.ques&answerPrefix=abc.answer

   --> faqAnswer injected successfully!!!

 * This call will generate 10 answers which answer prefix is "abc.answer" to questions "abc.ques0", "abc.ques1" and "abc.ques2".


*inject comment*

|===
|Parameter |Type |Description |Default value

|number
|mandatory
|The amount of injected comments
|

|toQues
|mandatory
|The question which injected comments are added to
|

|quesPrefix
|optional
|Define the question prefix
|"bench.ques"


|commentPrefix
|optional
|Define the comment prefix
|"bench.comment"
|===


   http://localhost:8080/rest/private/bench/inject/faqComment?number=10&toQues=0&quesPrefix=abc.ques&commentPrefix=abc.comment

  --> faqComment injected successfully!!!

 * This call will generate 10 comments which comment prefix is "abc.comment" to question "abc.ques0".


*inject attachment*

|===
|Parameter |Type |Description |Default value

|number
|mandatory
|The amount of injected attachments
|

|fromQues
|mandatory
|The begin of the question range which injected attachments are added to
|

|toQues
|mandatory
|The end of the question range which injected attachments are added to
|

|byteSize
|mandatory
|The size in byte unit of each added attachment
|

|quesPrefix
|optional
 |Define the question prefix
 |"bench.ques"
|===


   http://localhost:8080/rest/private/bench/inject/faqAttachment?number=10&fromQues=0&toQues=2&quesPrefix=abc.ques&byteSize=50

  --> faqAttachment injected successfully!!!

 * This call will generate 10 attachments which each file size is 50 bytes to question "abc.ques0", "abc.ques1" and "abc.ques2"


*inject Membership*

|===
|Parameter |Type |Description |Default value

|type
|mandatory
|must be set as 'category', 'question', or 'answer'
|

|toType
|mandatory
|Determines index of type for injection. ex: '5'
|

|typePrefix
|optional
|Define type of type prefix. ex: 'abc.cat' => for type is 'category'
|

|fromUser
|mandatory
|The begin of the user range
|

|toUser
|mandatory
|The end of the user range
|

|userPrefix
|optional
|Define the user prefix
|"bench.user"

|===

   http://localhost:8080/rest/private/bench/inject/faqMembership?type=category&toType=0&typePrefix=abc.cat&fromUser=0&toUser=2&userPrefix=abc.user

  --> faqMembership injected successfully!!!

 * This call will generate 3 memberships to category type with name is 'abc.cat0'


=== Poll Inject

We will describe how to use data injectors in eXo Poll

*inject grp*

|===
|Parameter |Type |Description |Default value

|number
|mandatory
|The amount of injected groups
|

|prefix
|optional
 |Define the group prefix
 |"bench.group"
|===


  http://localhost:8080/rest/private/bench/inject/pollGroup?number=20&prefix=abc.group

  --> pollGroup injected successfully!!!

  * This call will generate 20 groups.


*inject poll*

|===
|Parameter |Type |Description |Default value

|number
|mandatory
|The amount of injected polls for the group
|

|pollType
|mandatory
|The type of the Poll (public/private)
|

|groupPrefix
|optional
|Define the group prefix
|"bench.group"

|pollPrefix
|optional
|Define the poll prefix
|"bench.poll"

|toGroup
|mandatory
|The range of the group for injected polls
|

|===

  * *Public*

    http://localhost:8080/rest/private/bench/inject/pollPoll?pollType=public&number=10&pollPrefix=pub.poll

    -->  pollPoll injected successfully!!!

    ** This call will generate 10 public polls.


  * *Private*

    http://localhost:8080/rest/private/bench/inject/pollPoll?pollType=private&number=10&pollPrefix=pri.poll&groupPrefix=abc.group&toGroup=1

    --> pollPoll injected successfully!!!

    ** This call will generate 10 private polls for the group abc.group1.

*inject vote*

|===
|Parameter |Type |Description |Default value

|fromPoll
|mandatory
|The range of the poll for start vote polls
|

|toPoll
|mandatory
|The range of the poll for end vote polls
|

|pollPrefix
|optional
 |Define the poll prefix
 |"bench.poll"

|fromUser
|mandatory
|The begin of the user range
|

|toUser
|mandatory
|The end of the user range
|

|userPrefix
|optional
|Define the user prefix
|"bench.user"

|===


    http://localhost:8080/rest/private/bench/inject/pollVote?fromPoll=1&toPoll=100&pollPrefix=bench.poll&fromUser=10&toUser=50&userPrefix=abc.user

    --> pollVote injected successfully!!!

    * This call will voting 99 public polls [1 - 100] with poll prefix is bench.poll and with 40 users voting have index [10 - 50] with prefix is abc.user .



=== Note:
WIKI inject and ECMS inject doesn't work..So it must be reviewed .


== eXo Platform Compatibility

[caption=""]
|===
|eXo data-injectors Version  | eXo Platform Version


|1.0.x
|4.4.1

|1.0.x
|4.4.x

|1.0.x
|5.0.x
|===



=== Injection Custom


To create communitySpaces :
https://localhost:8080/rest/private/userinjection/communitySpaces?nbSpaces=3


To inject independant, profile data and collaborators, all can be done with one REST Call :
http://localhost:8080/rest/userinjection/usersandprofiles?nbIndependants=100&nbCollaborators=2&batchSize=10
will create 100 independants with 2 collaborators by independants.

batchSize is optionnal an indicate how many user we create before commiting the transaction.

To create collaborative spaces between independents and collaborators :
http://localhost:8080/rest/userinjection/collaborativesSpaces?nbSpaces=10&nbUsersBySpaces=3

nbSpaces : the number of spaces to creates
nbUsersBySpaces : the number of users to add in spaces

This service take the user list.
The first user is the creator of the space
The second if the first invited in the space
...
The nth is the nth invited in the space
The nth+1 is the creator of a new space
The nth+2 is invited in the new space
...
If we use all users, we go back to the first one, and loop, until create nbSpaces spaces.

An optionnal parameter can be passed :
usersOffset
This parameter allows to start the creation of spaces with a user different than the first one :
http://localhost:8080/rest/userinjection/collaborativesSpaces?nbSpaces=10&nbUsersBySpaces=3&usersOffset=1000









